### ISSUE TITLE
 cairosvg problem

### ISSUE THREAD

**Issue by jhonnyf37** [aelmiger/chessboard2fen#3]
Traceback (most recent call last):
  File "c:/Users/joaof/OneDrive/Área de Trabalho/21.2/Projeto Nivel 1 em Proc. Digital de Sinais/projeto/chessboard2fen/detectionScript.py", line 1, in <module>
    from chessboard import Chessboard
  File "c:\Users\joaof\OneDrive\Área de Trabalho\21.2\Projeto Nivel 1 em Proc. Digital de Sinais\projeto\chessboard2fen\chessboard.py", line 2, in <module>
    from cairosvg import svg2png
  File "C:\Users\joaof\AppData\Local\Programs\Python\Python37\lib\site-packages\cairosvg\__init__.py", line 26, in <module>     
    from . import surface  # noqa isort:skip
  File "C:\Users\joaof\AppData\Local\Programs\Python\Python37\lib\site-packages\cairosvg\surface.py", line 9, in <module>       
    import cairocffi as cairo
  File "C:\Users\joaof\AppData\Local\Programs\Python\Python37\lib\site-packages\cairocffi\__init__.py", line 50, in <module>    
    ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "C:\Users\joaof\AppData\Local\Programs\Python\Python37\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen      
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by ghost** [comment]
I used pipwin which install from an unofficial repository 

$ pip install pipwin
$ pipwin install cairocffi

Also see this related issue: [get cairosvg working in windows
(https://stackoverflow.com/questions/46265677/get-cairosvg-working-in-windows)
